# Generated by Django 4.0.1 on 2023-06-04 19:07

import OlympiadMainApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=255)),
                ('correct', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('type', models.CharField(choices=[('SCH', 'choose one'), ('MCH', 'choose several'), ('FUL', 'full answer'), ('CST', 'code with output comparison'), ('CDT', 'code with output test')], default='CST', max_length=3, verbose_name='Тип задачи')),
                ('choices', djongo.models.fields.JSONField(blank=True, default={}, null=True)),
                ('testinput', models.CharField(default=None, max_length=1000, primary_key=True, serialize=False, verbose_name='Текстовый ввод')),
                ('testoutput', models.CharField(max_length=1000, verbose_name='Текстовый вывод')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InnerTask',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание задачи')),
                ('description', models.TextField(max_length=10000, verbose_name='Полное описание задачи')),
                ('question', models.TextField(default=None, max_length=1000, verbose_name='Вопрос задачи')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Очки (вес)')),
                ('tests', djongo.models.fields.ArrayField(default=None, model_container=OlympiadMainApp.models.TestData, verbose_name='Тесты')),
                ('olympiad_id', djongo.models.fields.GenericObjectIdField(default=None, verbose_name='Ссылка на олимпиаду')),
                ('tasktype', models.CharField(choices=[('SCH', 'choose one'), ('MCH', 'choose several'), ('FUL', 'full answer'), ('CST', 'code with output comparison'), ('CDT', 'code with output test')], default='CST', max_length=3)),
                ('timeout', models.DurationField()),
                ('again', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='InnerTaskResult',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('task', djongo.models.fields.GenericObjectIdField(default=None, verbose_name='Ссылка на задачу')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Набранные очки')),
                ('finished', models.DateTimeField(default=None, verbose_name='Время успешного выполнения')),
                ('inner_attempts', models.PositiveIntegerField(verbose_name='количество попыток')),
                ('success', models.BooleanField(default=False, verbose_name='статус выполнения')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Чей результат')),
            ],
            options={
                'verbose_name': 'Пользовательский результат по задаче',
                'verbose_name_plural': 'результаты',
            },
        ),
        migrations.CreateModel(
            name='StandaloneTaskResult',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, verbose_name='Чей результат (имя пользователя)')),
                ('taskname', models.CharField(max_length=255, verbose_name='Для какой задачи (название)')),
                ('points', models.PositiveIntegerField(verbose_name='Вес в очках')),
                ('started', models.DateTimeField(default=None, verbose_name='Время начала выполнения')),
                ('finished', models.DateTimeField(default=None, verbose_name='Время начала выполнения')),
                ('attempts', models.PositiveIntegerField(verbose_name='количество попыток')),
                ('inner_attempts', models.PositiveIntegerField(verbose_name='количество внутренних отправлений')),
                ('success', models.BooleanField(default=False, verbose_name='статус выполнения')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Чей результат')),
            ],
            options={
                'verbose_name': 'Пользовательский результат по задаче',
                'verbose_name_plural': 'результаты',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='StandaloneTask',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название задачи')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание задачи')),
                ('description', models.TextField(max_length=10000, verbose_name='Полное описание задачи')),
                ('question', models.TextField(default=None, max_length=1000, verbose_name='Вопрос задачи')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Вес в очках')),
                ('active', models.BooleanField(default=True)),
                ('tests', djongo.models.fields.ArrayField(default=None, model_container=OlympiadMainApp.models.TestData, verbose_name='Тесты')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('since', models.DateTimeField(default=None, verbose_name='Активна с')),
                ('until', models.DateTimeField(default=None, verbose_name='Активна до')),
                ('results_number', models.PositiveBigIntegerField(default=0, verbose_name='Количество успешных результатов')),
                ('hidden', models.BooleanField(default=False, verbose_name='Закрытый доступ')),
                ('tasktype', models.CharField(choices=[('SCH', 'choose one'), ('MCH', 'choose several'), ('FUL', 'full answer'), ('CST', 'code with output comparison'), ('CDT', 'code with output test')], default='CST', max_length=3)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Создатель задачи')),
                ('results', djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='OlympiadMainApp.standalonetaskresult', verbose_name='Результаты пользователей')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadResult',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('olympiad', djongo.models.fields.GenericObjectIdField(default=None, verbose_name='Ссылка на олимпиаду')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Набранные очки')),
                ('started', models.DateTimeField(default=None, verbose_name='Время начала выполнения')),
                ('finished', models.DateTimeField(default=None, verbose_name='Время успешного выполнения')),
                ('attempts', models.PositiveIntegerField(verbose_name='количество попыток')),
                ('task_results', djongo.models.fields.ArrayReferenceField(default=None, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='OlympiadMainApp.innertaskresult', verbose_name='Результаты по задачам')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Чей результат')),
            ],
            options={
                'verbose_name': 'Пользовательский результат по задаче',
                'verbose_name_plural': 'результаты',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название олимпиады')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание олимпиады')),
                ('description', models.TextField(max_length=10000, verbose_name='Полное описание олимпиады')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('hidden', models.BooleanField(default=False, verbose_name='Закрытый доступ')),
                ('since', models.DateTimeField(default=None, verbose_name='Активна с')),
                ('until', models.DateTimeField(default=None, verbose_name='Активна до')),
                ('active', models.BooleanField(default=True)),
                ('finished', models.BooleanField(default=False)),
                ('access', djongo.models.fields.JSONField(blank=True, default={})),
                ('timeout', models.DurationField(default=None)),
                ('results_number', models.PositiveBigIntegerField(default=0, verbose_name='Количество успешных результатов')),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('results', djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='olympres', to='OlympiadMainApp.olympiadresult', verbose_name='Результаты участников')),
                ('tasks', djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='OlympiadMainApp.innertask', verbose_name='Список задач')),
            ],
            options={
                'verbose_name': 'Олимпиада',
                'verbose_name_plural': 'Олимпиады',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='innertask',
            name='results',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='OlympiadMainApp.innertaskresult', verbose_name='Результаты пользователей'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['name'], name='OlympiadMai_name_3ff5b4_idx'),
        ),
    ]
