--------------------------------------------------------
--  File created - קועגונד-ÿםגאנÿ-20-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FORMS_OF_EDUCATION
--------------------------------------------------------

  CREATE TABLE "ME"."FORMS_OF_EDUCATION" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_FORMS
--------------------------------------------------------

  CREATE UNIQUE INDEX "ME"."PK_FORMS" ON "ME"."FORMS_OF_EDUCATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FORMS_OF_EDUCATION
--------------------------------------------------------

  ALTER TABLE "ME"."FORMS_OF_EDUCATION" ADD CONSTRAINT "PK_FORMS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ME"."FORMS_OF_EDUCATION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ME"."FORMS_OF_EDUCATION" MODIFY ("ID" NOT NULL ENABLE);
